TC01 - User can log into Railway with valid username and password
thienan090196/selenium-an pull request #5
Opened 2021-05-04 07:17 UTC by thienan090196

2021-05-04 08:41 UTC, thanhlelgg commented on pom.xml
>  </project>
new line at EOF

2021-05-04 08:41 UTC, thanhlelgg commented on src/main/java/com/logigear/page_objects/HomePage.java
> +    public final Label lblWelcomeMessage = new Label(By.cssSelector(".account strong"));
don't use text formatting attribute in locator unless there's no other way

2021-05-04 08:41 UTC, thanhlelgg commented on src/main/java/com/logigear/page_objects/LoginPage.java
> +    private final TextBox txtEmail = new TextBox(By.cssSelector("input#username"));
why don't you just use By.id ?

2021-05-04 08:41 UTC, thanhlelgg commented on src/test/java/com/logigear/tests/LoginTest.java
> +        Assert.assertEquals(actualResult, expectedResult, actualResult + " is not matched with " + expectedResult);
no need to print the compare. assertEquals will do that when the test fail

2021-05-04 08:41 UTC, thanhlelgg commented on src/test/resources/TestNG.xml
> +</suite>
new line at EOF

2021-05-04 09:18 UTC, thienan090196 commented
@thanhlelgg I updated my code based on your request. Please review and let me know if any problems

2021-05-05 05:27 UTC, LoliSlayerMC requested changes

2021-05-05 05:27 UTC, LoliSlayerMC commented on src/main/java/com/logigear/helpers/DriverHelper.java
> +    private static final DriverHelper instance = new DriverHelper();
No need to create new instance. This is a helper class, so make all the necessary methods to public static modifier.

2021-05-05 05:27 UTC, LoliSlayerMC commented on src/test/java/com/logigear/tests/BaseTest.java
> +        DriverHelper.setWindowSize(Constant.DEFAULT_SCREEN_WIDTH, Constant.DEFAULT_SCREEN_HEIGHT);
We usually use `maximize()`, don't set a fixed screen size

2021-05-05 07:01 UTC, thienan090196 commented on src/main/java/com/logigear/helpers/DriverHelper.java
> +    private static final DriverHelper instance = new DriverHelper();
@LoliSlayerMC I had refactored my code and updated the latest one. Let me know if you have any questions or comments.

2021-05-05 07:01 UTC, thienan090196 commented on src/test/java/com/logigear/tests/BaseTest.java
> +        DriverHelper.setWindowSize(Constant.DEFAULT_SCREEN_WIDTH, Constant.DEFAULT_SCREEN_HEIGHT);
@LoliSlayerMC I had replaced the set window size to maximize. Please review and feedback to me

2021-05-05 07:06 UTC, LoliSlayerMC approved these changes
LGTM

2021-05-05 07:06 UTC, merged